### ISSUE TITLE
Decide on Structure & Nomenclature

### ISSUE THREAD

**Issue by flyingzumwalt** [flyingzumwalt/decentralized-web-primer#1]
I sketched out the tutorials using this structure & nomenclature:

> **Topic**
> -- Concepts, Prerequisites
> -- **Tutorial**
> ---- Goals, Steps, Explanation

I think it needs some tweaking. Better to tweak this stuff sooner rather than later.

## Examples of Other Structures 
The [RailsBridge Curriculum](http://curriculum.railsbridge.org) uses a slightly different nomenclature:

> **Curriculum**
> -- Goal, Meta Goal, Schedule, Requirements
> -- **Lesson**
> ---- Goals, Steps, Explanation

A more robust structure, as show in the [Jekyll Curriculum Template](http://flyingzumwalt.github.io/jekyll-curriculum-template/curriculum/) is:

> 
> **Curriculum**
> -- **Course**
> ---- Overview, Key Concepts, Learning Objectives
> ---- **Module**
> ------ Conceptual Framework, Learning Objectives
> ------ **Activity**
> -------- Conceptual Framework, Tasks

## Possible New Structure & Nomenclature

> **Tutorial**
>-- Prerequisites, Learning Objectives, Key Concepts, Conceptual Framework
> -- **Lesson**
> ---- Goals, Steps, Explanation

So, for example,

**Tutorial: Files on IPFS**
-- Prerequisites, Learning Objectives, Key Concepts, Conceptual Framework
-- **Lesson: Adding Files to IPFS and Retrieving Them**
---- Goals, Steps, Explanation
-- **Lesson: Pinning Files**
---- Goals, Steps, Explanation
-- **Lesson: Sharing Updates to Files using IPNS**
---- Goals, Steps, Explanation

**Comment by flyingzumwalt** [comment]
@RichardLitt any thoughts? (you can view the rendered book at https://flyingzumwalt.gitbooks.io/decentralized-web-primer)

**Comment by flyingzumwalt** [comment]
FYI: the structure I proposed makes a lot more sense, so I renamed/rearranged all the files to match that structure until/unless we decide on something better.

**Comment by RichardLitt** [comment]
I think your proposed final example makes the most sense. I like how you've really thought it out and not taken that for granted. I personally don't have much experience with designing these, so I don't feel fluent enough to respond based on what I've seen; but what you have at the bottom sounds good.

**Comment by flyingzumwalt** [comment]
Ok. Let's run with that structure & nomenclature for now. If it needs to change we can open a new ticket.
