### ISSUE TITLE
"Add content to IPFS": work in which directory?

### ISSUE THREAD

**Issue by jadrian** [flyingzumwalt/decentralized-web-primer#15]
In Step 1 of [`files-on-ipfs/lessons/add-and-retrieve-file-content.md`](https://github.com/flyingzumwalt/decentralized-web-primer/blob/e22f066d8ccdcc5954c020e50c35a7007c861750/files-on-ipfs/lessons/add-and-retrieve-file-content.md), it's not clear where one should create the example files.  The reality is that it doesn't matter, but the previous step (install/initialize IPFS) has you investigating `~/.ipfs`, which is *not* a good place to create test files.  The instructions should begin by telling the user to go to their homedir or anywhere else.

**Comment by RichardLitt** [comment]
Good idea! I opened #16 to address this. What do you think?

**Comment by jadrian** [comment]
Your patch is just right and resolves #15.  Thanks!
