### ISSUE TITLE
The link to the gitbook is broken.

### ISSUE THREAD

**Issue by Piliponful** [flyingzumwalt/decentralized-web-primer#20]
https://www.gitbook.com/read/book/flyingzumwalt/decentralized-web-primer/ - this link doesn't work. It used in the description of the repo and README.md.
https://dweb-primer.ipfs.io/SUMMARY.html - this link seems to work.

**Comment by flyingzumwalt** [comment]
Thanks. I had some troubles with gitbook recently, which is why we set up https://dweb-primer.ipfs.io at some point I will clean up all the references to the gitbook url but for now I've restored the gitbook copy.
